---
- hosts: '{{ target_hosts }}'
  become: true
  gather_facts: yes
  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Check for upgradable packages
      apt:
        update_cache: no
        state: present
      register: upgradable_packages

    - name: Display upgradable packages (Corrected Check)
      debug:
        msg: "Upgradable packages: {{ upgradable_packages.results.pkgs | map(attribute='pkg') | list }}"
      when: upgradable_packages.results is defined and upgradable_packages.results.pkgs is defined and upgradable_packages.results.pkgs | length > 0


    - name: Upgrade packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
        state: present
      register: upgrade_result

    - name: Display upgrade results
      debug:
        msg: "Upgraded packages: {{ upgrade_result.results | selectattr('changed') | map(attribute='pkg') | list }}"
      when: upgrade_result.results is defined and upgrade_result.changed

    - name: Display not upgraded packages
      debug:
        msg: "Not upgraded packages: {{ upgrade_result.results | rejectattr('changed') | map(attribute='pkg') | list }}"
      when: upgrade_result.results is defined and not upgrade_result.changed and upgrade_result.results is defined

    - name: Check if a reboot is needed (needs-restarting)
      command: needs-restarting -r
      register: needs_restarting_result
      changed_when: false  # Don't mark as changed because of the return code

    - name: Check if a reboot is needed (check-restart - more robust)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Check for host key change (check-restart)
      stat:
        path: /var/run/host-key-changed
      register: host_key_changed_file

    - name: Display reboot status
      debug:
        msg: "Reboot required (needs-restarting): {{ needs_restarting_result.rc == 0 }}"

    - name: Display reboot status (check-restart):
      debug:
        msg: "Reboot required (check-restart): {{ reboot_required_file.stat.exists }}"

    - name: Display host key change status:
      debug:
        msg: "Reboot required (host key changed): {{ host_key_changed_file.stat.exists }}"

    - name: Reboot the server if required (any condition)
      reboot:
        msg: "Rebooting server after package upgrades or host key change"
      when:
        - needs_restarting_result.rc == 0
        - reboot_required_file.stat.exists
        - host_key_changed_file.stat.exists
