---
- hosts: '{{ target_hosts }}'
  become: true
  gather_facts: yes
  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Check for upgradable packages
      apt:
        update_cache: no
        state: present
      register: upgradable_packages

    - name: Display upgradable packages (Corrected Check)
      debug:
        msg: "Upgradable packages: {{ upgradable_packages.results.pkgs | map(attribute='pkg') | list }}"
      when: upgradable_packages.results is defined and upgradable_packages.results.pkgs is defined and upgradable_packages.results.pkgs | length > 0


    - name: Upgrade packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
        state: present
      register: upgrade_result

    - name: Display upgrade results
      debug:
        msg: "Upgraded packages: {{ upgrade_result.results | selectattr('changed') | map(attribute='pkg') | list }}"
      when: upgrade_result.results is defined and upgrade_result.changed

    - name: Display not upgraded packages
      debug:
        msg: "Not upgraded packages: {{ upgrade_result.results | rejectattr('changed') | map(attribute='pkg') | list }}"
      when: upgrade_result.results is defined and not upgrade_result.changed and upgrade_result.results is defined

    # ... (Reboot checks and reboot task - same as before) ...
